In [3]:
import pandas as pd

df = pd.read_csv("df_pca.csv")

df.head()

,Week_End,Week_Start_Fri,Week_Label,Weekly_Rank,id,Title,Artists_All,Weekly_Points,Streams,Days_Charted,...,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,Song_URL,PC1,PC2,PC3,PC4
0,2017/1/6,2016/12/31,2016-12-31 → 2017-01-06,1,5aAx2yezTd8zXrkmtKl66Z,Starboy,"The Weeknd, Daft Punk",1198,NaN,6.0,...,-7.028,0.282,0.165,0.0,0.535,https://open.spotify.com/track/5aAx2yezTd8zXrk...,0.093323,1.486236,0.479126,-1.053577
1,2017/1/6,2016/12/31,2016-12-31 → 2017-01-06,2,7BKLCZ1jbUBVqRi2FVlTVw,Closer,"The Chainsmokers, Halsey",1192,NaN,6.0,...,-5.599,0.034,0.414,0.0,0.661,https://open.spotify.com/track/7BKLCZ1jbUBVqRi...,-0.071947,0.215021,-0.988435,0.958771
2,2017/1/6,2016/12/31,2016-12-31 → 2017-01-06,3,5knuzwU65gJK7IF5yJsuaW,Rockabye (feat. Sean Paul & Anne-Marie),Clean Bandit,1185,NaN,6.0,...,-4.068,0.052,0.406,0.0,0.742,https://open.spotify.com/track/5knuzwU65gJK7IF...,1.040625,-0.218344,-0.742067,0.919837
3,2017/1/6,2016/12/31,2016-12-31 → 2017-01-06,4,4pdPtRcBmOSQDlJ3Fk945m,Let Me Love You,"DJ Snake, Justin Bieber",1176,NaN,6.0,...,-5.309,0.058,0.078,0.0,0.142,https://open.spotify.com/track/4pdPtRcBmOSQDlJ...,-0.361769,-1.774901,0.536522,-1.350242
4,2017/1/6,2016/12/31,2016-12-31 → 2017-01-06,5,3NdDpSvN911VPGivFlV5d0,I Don't Wan Live Forever (Fifty Shades Darker)...,"ZAYN, Taylor Swift",1170,NaN,6.0,...,-8.374,0.059,0.063,0.0,0.086,https://open.spotify.com/track/3NdDpSvN911VPGi...,-1.202927,-0.118441,0.343824,-0.897204

In [4]:
features = [
    "Danceability", "Energy", "Loudness",
    "Speechiness", "Acousticness",
    "Instrumentalness", "Valence"
]

table2 = df.groupby("Stage")[features].agg(["mean", "std"]).round(3)

table2

                    Danceability        Energy        Loudness         \
                            mean    std   mean    std     mean    std
Stage
Stage 1 (2017-2019)        0.699  0.131  0.641  0.159   -6.023  2.324
Stage 2 (2020-2022)        0.680  0.145  0.632  0.162   -6.212  2.404
Stage 3 (2023-2025)        0.640  0.150  0.639  0.171   -6.674  3.636

                    Speechiness        Acousticness        Instrumentalness  \
                           mean    std         mean    std             mean
Stage
Stage 1 (2017-2019)       0.117  0.104        0.217  0.224            0.007
Stage 2 (2020-2022)       0.104  0.096        0.259  0.257            0.010
Stage 3 (2023-2025)       0.074  0.071        0.256  0.264            0.022

                           Valence
                       std    mean    std
Stage
Stage 1 (2017-2019)  0.050   0.495  0.217
Stage 2 (2020-2022)  0.065   0.513  0.233
Stage 3 (2023-2025)  0.108   0.508  0.238