In [1]:
import pandas as pd

df = pd.read_csv("df_clustered.csv")

df.head()

,Week_End,Week_Start_Fri,Week_Label,Weekly_Rank,id,Title,Artists_All,Weekly_Points,Streams,Days_Charted,...,Acousticness,Instrumentalness,Valence,Song_URL,PC1,PC2,PC3,PC4,Cluster,Cluster_Name
0,2017/1/6,2016/12/31,2016-12-31 → 2017-01-06,1,5aAx2yezTd8zXrkmtKl66Z,Starboy,"The Weeknd, Daft Punk",1198,NaN,6.0,...,0.165,0.0,0.535,https://open.spotify.com/track/5aAx2yezTd8zXrk...,0.093323,1.486236,0.479126,-1.053577,0,Hip-hop / Rap Dance
1,2017/1/6,2016/12/31,2016-12-31 → 2017-01-06,2,7BKLCZ1jbUBVqRi2FVlTVw,Closer,"The Chainsmokers, Halsey",1192,NaN,6.0,...,0.414,0.0,0.661,https://open.spotify.com/track/7BKLCZ1jbUBVqRi...,-0.071947,0.215021,-0.988435,0.958771,2,Energetic Pop
2,2017/1/6,2016/12/31,2016-12-31 → 2017-01-06,3,5knuzwU65gJK7IF5yJsuaW,Rockabye (feat. Sean Paul & Anne-Marie),Clean Bandit,1185,NaN,6.0,...,0.406,0.0,0.742,https://open.spotify.com/track/5knuzwU65gJK7IF...,1.040625,-0.218344,-0.742067,0.919837,2,Energetic Pop
3,2017/1/6,2016/12/31,2016-12-31 → 2017-01-06,4,4pdPtRcBmOSQDlJ3Fk945m,Let Me Love You,"DJ Snake, Justin Bieber",1176,NaN,6.0,...,0.078,0.0,0.142,https://open.spotify.com/track/4pdPtRcBmOSQDlJ...,-0.361769,-1.774901,0.536522,-1.350242,2,Energetic Pop
4,2017/1/6,2016/12/31,2016-12-31 → 2017-01-06,5,3NdDpSvN911VPGivFlV5d0,I Don't Wan Live Forever (Fifty Shades Darker)...,"ZAYN, Taylor Swift",1170,NaN,6.0,...,0.063,0.0,0.086,https://open.spotify.com/track/3NdDpSvN911VPGi...,-1.202927,-0.118441,0.343824,-0.897204,1,Mellow Acoustic

In [2]:
df.columns

Index(['Week_End', 'Week_Start_Fri', 'Week_Label', 'Weekly_Rank', 'id',
       'Title', 'Artists_All', 'Weekly_Points', 'Streams', 'Days_Charted',
       'Peak_Rank', 'Stage', 'Year', 'Danceability', 'Energy', 'Loudness',
       'Speechiness', 'Acousticness', 'Instrumentalness', 'Valence',
       'Song_URL', 'PC1', 'PC2', 'PC3', 'PC4', 'Cluster', 'Cluster_Name'],
      dtype='str')

In [3]:
features = [
    "Danceability", "Energy", "Loudness",
    "Speechiness", "Acousticness",
    "Instrumentalness", "Valence"
]

cluster_table = (
    df.groupby("Cluster_Name")[features]
      .mean()
      .round(3)
)

cluster_counts = df["Cluster_Name"].value_counts()

cluster_table["n"] = cluster_counts

cluster_table

,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,n
Cluster_Name,,,,,,,,
Energetic Pop,0.707,0.729,-4.991,0.071,0.145,0.003,0.600,51086
Hip-hop / Rap Dance,0.760,0.600,-6.685,0.273,0.196,0.005,0.470,14622
Instrumental,0.494,0.439,-15.081,0.072,0.334,0.605,0.245,1216
Mellow Acoustic,0.565,0.479,-8.320,0.056,0.471,0.008,0.344,24785